/**
 * @file      ti_msp_dl_config.h
 * @brief     Fake DriverLib / SysConfig header for host-compiled adapter tests
 * @note      This file is ONLY used when building temp/tests/test_mspm0_adapter.c
 *            on the host. The real header is generated by SysConfig on the MSPM0
 *            target build.
 */

#ifndef _TI_MSP_DL_CONFIG_H_
#define _TI_MSP_DL_CONFIG_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ----------------------------------------------------------------------
 * Fake register-bank type stubs (empty - never dereferenced in tests)
 * ---------------------------------------------------------------------- */
typedef struct { uint8_t _unused_spi; }    SPI_Regs;
typedef struct { uint8_t _unused_gpio; }   GPIO_Regs;
typedef struct { uint8_t _unused_timer; }  GPTIMER_Regs;

/* ----------------------------------------------------------------------
 * SysConfig symbol contract
 * ---------------------------------------------------------------------- */
#define SPI1_INST              ((SPI_Regs *)1)
#define ICM42688_PORT          ((GPIO_Regs *)2)
#define ICM42688_CS_PIN        (1U << 20)
#define ICM42688_TIMER_INST    ((GPTIMER_Regs *)3)
#define CPUCLK_FREQ            32000000U

/* ----------------------------------------------------------------------
 * DriverLib function declarations (implemented in the test file)
 * ---------------------------------------------------------------------- */
void     DL_GPIO_clearPins(GPIO_Regs *port, uint32_t pins);
void     DL_GPIO_setPins(GPIO_Regs *port, uint32_t pins);
void     DL_SPI_transmitDataBlocking8(SPI_Regs *spi, uint8_t data);
uint8_t  DL_SPI_receiveDataBlocking8(SPI_Regs *spi);
uint32_t DL_TimerG_getTimerCount(GPTIMER_Regs *timer);
void     delay_cycles(uint32_t cycles);

#ifdef __cplusplus
}
#endif

#endif /* _TI_MSP_DL_CONFIG_H_ */
